### ISSUE TITLE
Possible to sign or release a checksum alongside release?

### ISSUE THREAD

**Issue by ropnop** [whitesource/unified-agent-distribution#1]
Hello - it would be beneficial for us to verify the JAR after downloading it in our pipelines. Could you release a checksum or (even better) sign the JAR and let us verify it with a public key? That way we could verify it after downloading in a pipeline but before executing it. Thanks

**Comment by SenuraMalaka** [comment]
The checksums are posted in [here](https://whitesource.atlassian.net/wiki/spaces/WD/pages/33718339/Unified+Agent#UnifiedAgent-Installation) for each release. 
![image](https://user-images.githubusercontent.com/19330762/74732999-6d7e5780-5271-11ea-83c0-25ef78f65917.png)

**Comment by annarozin** [comment]
please see @SenuraMalaka  answer
