### ISSUE TITLE
error in execute command 'mvn -T1 dependency:tree -DoutputFile=whitesource_mvn_dependency_tree.txt -B', Exit Status 1

### ISSUE THREAD

**Issue by darveshsingh** [whitesource/unified-agent-distribution#11]
Hi team,

Hope you are doing good and staying well 💯 

I've temporary done a workaround for the issue by running a clean install.

However, according to this article: https://stackoverflow.com/questions/28835418/mvn-dependencytree-fails-on-trivial-project. It seems that we have to clean and install all the jar files locally before running the dependency tree.

This seems to be a maven behaviour.

This seems to happen for SNAPSHOT builds.

**Comment by darveshsingh** [comment]
Hello @LenaKleyner ,

Thank you for your response. :)
I am using the whitesource's Unified agent. Is it possible to set parameter that way?

Following is a sample
java -jar /path/to/wss-unified-agent-20.11.1.jar -c current/folder/whitesource/wss-unified-agent.config

**Comment by LenaKleyner** [comment]
@darveshsingh, sure, this parameter can be set in the [config file](https://whitesource.atlassian.net/wiki/spaces/WD/pages/1544880156/Unified+Agent+Configuration+Parameters#Maven) or passed as an [environment variable](https://whitesource.atlassian.net/wiki/spaces/WD/pages/1544880156/Unified+Agent+Configuration+Parameters#Configuring-the-Unified-Agent-by-Environment-Variables).

**Comment by annarozin** [comment]
@darveshsingh  I am closing this issue, feel free to reopen or contact support if you have follow-up questions.
Thanks,
Anna

**Comment by annarozin** [comment]
@darveshsingh I am closing this issue, feel free to reopen or contact support if you have follow-up questions.
Thanks,
Anna
