### ISSUE TITLE
Version 21.6.2 wrongly interprets`gradle.preferredEnvironment`

### ISSUE THREAD

**Issue by tkurylek** [whitesource/unified-agent-distribution#14]
Hello Whitesource Team!

According to the documentation of [Unified Agent Configuration](https://whitesource.atlassian.net/wiki/spaces/WD/pages/1544880156/Unified+Agent+Configuration+Parameters#Gradle) when `gradle.preferredEnvironment` is set to `wrapper` the `gradlew` command will be used instead of `gradle` to execute gradle CLI. 
However, since `21.6.2` the library seems to accept only `gradle.preferredEnvironment=gradlew` for this purpose, ignoring `gradle.preferredEnvironment=wrapper` and introducing incompatibility between `21.6.2` and `21.6.1` versions.

Could you correct the documentation page or accept the old `wrapper` value in `21.6.2`?

Thank you.

**Comment by LenaKleyner** [comment]
@tkurylek thanks for opening this.

We've just released a fix [21.6.2.2](https://whitesource.atlassian.net/wiki/spaces/WD/pages/33718455/WhiteSource+Server+Release+Notes#Version-21.6.2.2-(6-July-2021)) addressing this. Please let us know if this indeed resolved this issue.

Thanks,

Lena

**Comment by tkurylek** [comment]
Hi @LenaKleyner
I can confirm that the issue is resolved in this version. 
Thank you for looking at this so quickly!
