### ISSUE TITLE
generateScanReport doesn't work with UA Version 21.12.1

### ISSUE THREAD

**Issue by joaquin386** [whitesource/unified-agent-distribution#24]
Hi

We have the parameter generateScanReport=true and scanReportFilenameFormat=static for UA 21.12.1 and the scan_report.json is not written to whitesource/scan_report.json. We even have this from the logs:
```
scan report created successfully at /vsts/agent/_work/24/s/./whitesource/scan_report.json
```
But when checking there is NO folder or NO file with the scan_report.json name.

We had before the upgrade the UA 21.11.2 and the report was generated correctly, we have to disable now the WS scanning because the automation was base on that file. 

This started happening the moment UA was upgraded o 21.12.1 (was working on 21.11.2)

BR

Joaquin

**Comment by LenaKleyner** [comment]
Hi @joaquin386 , we will need more information to evaluate your issue. 
Could you please open a support ticket with all the relevant information (the Unified Agent execution command, its settings, and the output log)?

Thanks!

Lena

**Comment by joaquin386** [comment]
You have the case open now at your end. Logs provided where all the above is shown. Still the logs show this:
```
scan report created successfully at /vsts/agent/_work/24/s/./whitesource/scan_report.json
```
Seems as the logs is writing the file but then doing a `ls -al` of `/vsts/agent/_work/24/s/` doesnt show the `whitesource` directory or the file that has to be created inside it.

**Comment by kostukp96** [comment]
in 21.12.2 doesnt work to...

**Comment by kostukp96** [comment]
@joaquin386 did you manage to solve this problem?

**Comment by joaquin386** [comment]
Yes this parameter suddenly was needed after the upgrade.
`log.files.level`

So now it is working and yes the case can be closed. I can do it if you want.

**Comment by kostukp96** [comment]
@joaquin386 Can you tell me where I need to set this parameter?

**Comment by joaquin386** [comment]
You have the documentation here: https://whitesource.atlassian.net/wiki/spaces/WD/pages/1544880156/Unified+Agent+Configuration+Parameters

So either you pass it as a env variable `WS_log.files.level=INFO` or you pass it together with your Whitesource execution command `/usr/bin/java -jar /vsts/agent/_work/whitesource_agent/wss-unified-agent.jar ..... -log.files.level Info`

So you have to options whichever fits you best

**Comment by djwgit** [comment]
@joaquin386 
with UA version 22.6.2
I tried your solution setting -log.files.level Info,  got a smaller log file, since default is Debug.
but still no report json generated...  wonder if it still works for you with this latest UA version... thanks
