### ISSUE TITLE
generateScanReport doesn't work with UA Version 21.12.2

### ISSUE THREAD

**Issue by kostukp96** [whitesource/unified-agent-distribution#26]
From this issue #24 scan report doesnt work in Version 21.12.2
In log file i can see "scan report created successfully at /vsts/agent/_work/24/s/./whitesource/scan_report.json", but if i check this source, i cant find ./whitesource/scan_report.json...
I need this report for create new item in my board, its important for me...

Do you have any ideas how to fix this?

**Comment by LenaKleyner** [comment]
Hi @kostukp96 ,

We are looking into this. 
Could you please open a support ticket with all the relevant information (the Unified Agent execution command, its settings, and the output log)?

Thanks!

Lena

**Comment by kostukp96** [comment]
thanks i did it

**Comment by LenaKleyner** [comment]
Hi @kostukp96 , we have resolved the underlying issue that caused this is in release 22.2.1 of the Unified Agent. 
I am closing this, feel free to reopen if the issue persists.
