### ISSUE TITLE
Missing wss-unified-agent.jar

### ISSUE THREAD

**Issue by chrisbardon** [whitesource/unified-agent-distribution#4]
My Azure devops pipeline is pulling the agent from https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss-unified-agent.jar, but the file appears to be missing.  Is this intentional?  I see it was deleted on Apr 12, but never replaced.

**Comment by annarozin** [comment]
Hi Chris,
Please use the following URL https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar as described in https://github.com/whitesource/unified-agent-distribution/blob/master/standAlone/wss_agent.sh
Thanks
