### ISSUE TITLE
About pnpm support

### ISSUE THREAD

**Issue by shiruco** [whitesource/unified-agent-distribution#41]
Hi, Team. 
I'm using `pnpm` in my project and CVE issues are not detected.
Does unified agent support pnpm (pnpm-lock.yaml)? If not, do you plan to support it in the future?

**Comment by LenaKleyner** [comment]
Hi @shiruco, `pnpm` is not supported currently. 
This is something we are evaluating but there are no concrete plans at the moment.

**Comment by shiruco** [comment]
@LenaKleyner 
Thank you for your reply.
I am using `mend for github` and it also uses unified agent internally, so I cannot detect CVE issues when using pnpm, right?

**Comment by avinoamw1** [comment]
@shiruco 

That is correct.

**Comment by shiruco** [comment]
Thanks!
