### ISSUE TITLE
Correct metadata in the wss-unified-agent jar file

### ISSUE THREAD

**Issue by hakanai** [whitesource/unified-agent-distribution#8]
The wss-unified-agent jar file's META-INF/MANIFEST.MF is missing the version number normally expected to be in jar files.

As best I can tell, the current version is actually 21.1.2.1? Based on the maven POM file for wss-unified-agent-main found in the same jar file.

**Comment by LenaKleyner** [comment]
Hi @hakanai , 

First of all, sorry for the late response.
Secondly, the version of the Unified Agent is being exposed in the `project.properties` file within the JAR and can also be retried using the -v [option](https://whitesource.atlassian.net/wiki/spaces/WD/pages/1544880156/Unified+Agent+Configuration+Parameters#Command-Line-Parameters). 
Can one of these suggested options fit your needs or do you still expect the version to be reflected in the `META-INF/MANIFEST.MF` file?

Thanks,

Lena

**Comment by hakanai** [comment]
We can certainly get it from there, but it's still best to follow the standards.

**Comment by LenaKleyner** [comment]
Hi @hakanai, 

The version number now appears at the `META-INF/MANIFEST.MF` starting release 21.10.2. 
Thanks for bringing this up.

Lena

**Comment by nabeelsaabna** [comment]
closing the issue
