### ISSUE TITLE
Publish an updated version on a Maven repo

### ISSUE THREAD

**Issue by hakanai** [whitesource/unified-agent-distribution#9]
As is almost needless to say, projects wishing to use a tool would have a better time integrating if the tool were available on a Maven repository.

The latest version of wss-unified-agent available on a Maven repository is 19.7.3, published in 2019:

https://mvnrepository.com/artifact/org.whitesource/wss-unified-agent/19.7.3

This version is actually missing 3/4 of the contents of the jar, rendering it unusable. The current version available on this repo, though, does work, and should probably be published to the Maven repo, Otherwise, it's inconvenient for projects to actually get the jar and use it.

**Comment by annarozin** [comment]
The unified agent is no longer published to mvn repo

**Comment by hakanai** [comment]
Hence why the ticket was filed, asking for it to be published.

**Comment by hakanai** [comment]
You do know that GitHub can act as a Maven repository, right? Even just making sure to publish it there would be much better than publishing it nowhere.

**Comment by LenaKleyner** [comment]
Hi @hakanai, 

Sorry for the inconvenience and the late response. 
My name is Lena, I'm the Product Owner of the Unified Agent and will be happy to assist. 
The Unified Agent has been closed source since the beginning of 2019, therefore we stopped publishing it to Maven Central. In addition, we have deprecated all of our old plugins in favor of the Unified Agent, which has full parity with them, in addition to a wider set of capabilities. I'd be happy to have a quick walkthrough.

**Comment by hakanai** [comment]
We know how to run the unified agent.

The thing is, though, we _still_ have to integrate the thing into Gradle, because that's how the software is built. So the only result is that we're forced to write our own plugin to do it. Many other users are likely forced to react in the same way, so all this really equates to is a few hours of wasted time multiplied by howevery many people are trying to use the tool. Would it not be more efficient for WhiteSource to develop the Gradle plugin and save all this time? Unless the number of people using the software is diminishingly small.

**Comment by hakanai** [comment]
(Additionally, I don't think that something going closed source _necessarily_ means that you have to make it annoying to use!)

**Comment by LenaKleyner** [comment]
I'm sorry for the inconvenience. 
It's definitely not designed to be annoying and I'd be happy to work with you to change that. 
As mentioned, the Unified Agent is not an open-source project. With that being said, I would like to understand better the suggested options to make the tool easier to use.

**Comment by hakanai** [comment]
The agent itself need not be an open source project, but the company should provide an API to run the agent and an open source core library to use the API. Then a Gradle plugin uses that API and gives as minimalistic an interface as possible for the end user, perhaps with configuration variable specifying the server to get the agent from.

**Comment by hakanai** [comment]
A lot of the commercial jars we depend on self-host. This would be the first one on GitHub but I suspect it should work. It should be mirrorable like most repos.
